### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by boxydog** [inovex/CalendarSync#256]
I'm trying out the project. I'm on a 2015 macbook pro.

I'm trying to sync google calendar one => two. (Actually, I have 3 accounts, and I'm eventually going to try syncing from each to the other, so I've set them all up, and I'm just trying one sync for now.)

I installed everything, did the google cloud console project creates, set up a sync yaml file.

When I run a sync (--dry-run or not), I get a panic, pasted below.

The chance that I chose the wrong account on the oauth screen, or made some other mistake, is high.

I wonder if it's possible to have a more informative error message than the panic, to help me debug.

=== calendarsync version:

```
$ calendarsync --version
Version: 0.10.1
```

=== one_to_two_sync.yaml (mostly defaults, some details hidden)

```
---
sync:
  start:
    identifier: MonthStart # 1st of the current month
    # offset: -1 # MonthStart -1 month (beginning of last month)
  end:
    identifier: MonthEnd # last day of the current month
    offset: +1 # MonthEnd +1 month (end of next month)

auth:
  storage_mode: yaml # Currently, only yaml is supported
  config:
    # Here you can use the standard unix abbreviation for home directory (~).
    # This works also for Windows systems e.g. ~\calendar-sync\auth-storage.yaml
    path: "./auth-storage.yaml"

sink:
  adapter:
    type: google
    calendar: "two.."
    oAuth:
      clientId: 1...
      clientKey: G...

source:
  adapter:
    type: google
    calendar: "one.."
    oAuth:
      clientId: 1...
      clientKey: G...

transformations:
  - name: KeepDescription
  - name: KeepLocation
  - name: KeepReminders
  - name: ReplaceTitle
    config:
      # NewTitle: "[Synchronisierter Termin]"
      NewTitle: "[sync]"
  - name: KeepMeetingLink
  # Do not use KeepAttendees when the Outlook Adapter is used as a sink. There is no way to suppress mail invitations
  - name: KeepAttendees
    config:
      UseEmailAsDisplayName: true

# Filters remove events from being synced due to different criteria
filters:
  # Events where you declined the invitation aren't synced
  - name: DeclinedEvents
  # Events which cover the full day aren't synced
  - name: AllDayEvents
  # Events within the specified timeframe will be retained, while all others will be filtered out.
  # hours are represented in the 24h time format
  - name: TimeFrame
    config:
      HourStart: 8
      HourEnd: 17
  # Events where the title matches the ExcludeRegexp (RE2 Regex) aren't synced
  - name: RegexTitle
    config:
      ExcludeRegexp: ".*test"

# Perform multiple calendar updates concurrently
# Defaults to 1 if not set
updateConcurrency: 3
```

=== error:

```
calendarsync-dir $ calendarsync --config sync_one_to_two.yaml
5:28PM INFO loaded config file path=sync_one_to_two.yaml
5:28PM INFO using stored credentials adapter=google type=source
5:28PM INFO loaded source adapter adapter=google calendar=...
5:28PM INFO using stored credentials adapter=google type=sink
5:28PM INFO loaded sink adapter adapter=google calendar=...
5:28PM INFO loaded sync controller
5:28PM INFO loaded 38 events between Sun, 01 Jun 2025 00:00:00 CDT and Wed, 30 Jul 2025 00:00:00 CDT. adapter=google type=source
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x168ca14]

goroutine 1 [running]:
github.com/inovex/CalendarSync/internal/adapter/google.calendarEventToEvent(0xc000037180, {0xc0001776e0?, 0x1ea8820?})
	/home/runner/work/CalendarSync/CalendarSync/internal/adapter/google/event.go:30 +0x214
github.com/inovex/CalendarSync/internal/adapter/google.(*GCalClient).ListEvents(0xc00048ba00, {0x19d65b8?, 0x1f8c0e0}, {0xc0105bea20?, 0x100f9c9?, 0x1f5cbe0?}, {0xc00012ce70?, 0xc00012ab00?, 0x1f5cbe0?})
	/home/runner/work/CalendarSync/CalendarSync/internal/adapter/google/client.go:72 +0x99d
github.com/inovex/CalendarSync/internal/adapter/google.(*CalendarAPI).EventsInTimeframe(0xc0004a4230, {0x19d65b8?, 0x1f8c0e0?}, {0xc00003a7b0?, 0xc0105bea98?, 0x1f5cbe0?}, {0x14?, 0xc0105beae0?, 0x1f5cbe0?})
	/home/runner/work/CalendarSync/CalendarSync/internal/adapter/google/adapter.go:176 +0x79
github.com/inovex/CalendarSync/internal/adapter.SinkAdapter.EventsInTimeframe(...)
	/home/runner/work/CalendarSync/CalendarSync/internal/adapter/sink_adapter.go:104
github.com/inovex/CalendarSync/internal/sync.Controller.loadEvents({{0x19d4f40, 0xc00048b800}, {0xc00011e700, 0x6, 0x8}, {0xc00048bcc0, 0x4, 0x4}, {0x19d7988, 0xc00048bb80}, ...}, ...)
	/home/runner/work/CalendarSync/CalendarSync/internal/sync/controller.go:59 +0x202
github.com/inovex/CalendarSync/internal/sync.Controller.SynchroniseTimeframe({{0x19d4f40, 0xc00048b800}, {0xc00011e700, 0x6, 0x8}, {0xc00048bcc0, 0x4, 0x4}, {0x19d7988, 0xc00048bb80}, ...}, ...)
	/home/runner/work/CalendarSync/CalendarSync/internal/sync/controller.go:75 +0x7e
main.Run(0xc00048afc0)
	/home/runner/work/CalendarSync/CalendarSync/cmd/calendarsync/main.go:202 +0xe06
github.com/urfave/cli/v2.(*Command).Run(0xc00019b340, 0xc00048afc0, {0xc000034150, 0x3, 0x3})
	/home/runner/work/CalendarSync/CalendarSync/vendor/github.com/urfave/cli/v2/command.go:276 +0x9dd
github.com/urfave/cli/v2.(*App).RunContext(0xc0001c3800, {0x19d65b8?, 0x1f8c0e0}, {0xc000034150, 0x3, 0x3})
	/home/runner/work/CalendarSync/CalendarSync/vendor/github.com/urfave/cli/v2/app.go:333 +0x5db
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/work/CalendarSync/CalendarSync/vendor/github.com/urfave/cli/v2/app.go:307
main.main()
	/home/runner/work/CalendarSync/CalendarSync/cmd/calendarsync/main.go:98 +0x4ac
        
```
