### ISSUE TITLE
Proposal: Filter events to sync

### ISSUE THREAD

**Issue by vrld** [inovex/CalendarSync#65]
There may be calender events that I do not want to sync, like duplicates or reminders of private events. We could add an optional section similar to `transformations`, e.g.:

```yaml
filters:
  - name: Regex
    config:
      Pattern: "(foo|bar)"
  - name: TimeFrame
    config:
      From: "0:00"
      Until: "8:00"
```
